# Generated by Django 5.0 on 2023-12-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('MatchID', models.AutoField(primary_key=True, serialize=False)),
                ('MatchDate', models.DateField()),
            ],
            options={
                'db_table': 'matches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('PlayerID', models.AutoField(primary_key=True, serialize=False)),
                ('playerName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'players',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchStatistic',
            fields=[
                ('StatID', models.AutoField(primary_key=True, serialize=False)),
                ('MinutesPlayed', models.IntegerField()),
                ('TwoPointsMade', models.IntegerField()),
                ('TwoPointsAttempt', models.IntegerField()),
                ('TwoPointsPercentage', models.FloatField()),
                ('ThreePointsMade', models.IntegerField()),
                ('ThreePointsAttempt', models.IntegerField()),
                ('ThreePointsPercentage', models.FloatField()),
                ('FreeThrowMade', models.IntegerField()),
                ('FreeThrowAttempt', models.IntegerField()),
                ('FreeThrowPercentage', models.FloatField()),
                ('OffensiveRebound', models.IntegerField()),
                ('DefensiveRebound', models.IntegerField()),
                ('TotalRebound', models.IntegerField()),
                ('Assists', models.IntegerField()),
                ('Turnovers', models.IntegerField()),
                ('Steals', models.IntegerField()),
                ('Blocks', models.IntegerField()),
                ('Fouls', models.IntegerField()),
                ('FoulsOn', models.IntegerField()),
                ('Efficency', models.IntegerField()),
                ('TotalPoints', models.IntegerField()),
            ],
            options={
                'db_table': 'PlayerMatchStatistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('TeamID', models.AutoField(primary_key=True, serialize=False)),
                ('TeamName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'teams',
                'managed': False,
            },
        ),
    ]
